/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Introspect the authenticated API key */
    get: operations['MeController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List batches for the authenticated tenant */
    get: operations['PublicBatchesController_list'];
    put?: never;
    /**
     * Mint a new batch of units
     * @description Idempotent on Idempotency-Key: a repeated key with the same body replays the original 202; a repeated key with a different body 409s.
     */
    post: operations['PublicBatchesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batches/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single batch */
    get: operations['PublicBatchesController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batches/{id}/units': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the units minted into a batch */
    get: operations['PublicBatchesController_units'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/units/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single unit (tier-2 code never returned) */
    get: operations['PublicUnitsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/units/{id}/flag': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Flag a unit as suspicious */
    post: operations['PublicUnitsController_flag'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/units/{id}/decommission': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decommission a unit (confirmed counterfeit, recalled, etc.) */
    post: operations['PublicUnitsController_decommission'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/units/{id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a flagged or decommissioned unit to active */
    post: operations['PublicUnitsController_restore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List scan events for the authenticated tenant */
    get: operations['PublicScansController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List consumer fake-reports for the authenticated tenant */
    get: operations['PublicReportsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single report */
    get: operations['PublicReportsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDetailDto: {
      field?: string;
      issue: string;
    };
    ErrorBodyDto: {
      /** @enum {string} */
      type:
        | 'not_found'
        | 'validation'
        | 'unauthorized'
        | 'forbidden'
        | 'rate_limited'
        | 'conflict'
        | 'idempotency_mismatch'
        | 'plan_limit'
        | 'internal';
      message: string;
      requestId?: string;
      docs: string;
      details?: components['schemas']['ErrorDetailDto'][];
    };
    ErrorResponseDto: {
      error: components['schemas']['ErrorBodyDto'];
    };
    RateLimitDto: {
      perMinute: number;
    };
    MeResponseDto: {
      tenantId: string;
      /** @example vk_live_3f9a */
      keyPrefix: string;
      scopes: string[];
      rateLimit: components['schemas']['RateLimitDto'];
    };
    CreatePublicBatchDto: {
      productId: string;
      oemId: string;
      count: number;
      note?: string;
    };
    BatchResponseDto: {
      id: string;
      tenantId: string;
      productId: string;
      oemId: string | null;
      count: number;
      /** @enum {string} */
      status:
        | 'minting'
        | 'minted'
        | 'delivered'
        | 'printed'
        | 'shipped'
        | 'closed'
        | 'failed';
      mintedCount: number;
      watermark: string;
      kid: string;
      note: string | null;
      /** Format: date-time */
      expectedShipDate: string | null;
      /** Format: date-time */
      mintedAt: string | null;
      /** Format: date-time */
      exportsReadyAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateBatchResponseDto: {
      batch: components['schemas']['BatchResponseDto'];
      exportUrl: string | null;
    };
    BatchesPageDto: {
      data: components['schemas']['BatchResponseDto'][];
      nextCursor: string | null;
    };
    UnitResponseDto: {
      id: string;
      tenantId: string;
      batchId: string;
      productId: string;
      tier1Code: string;
      /** @description First 8 hex chars of the tier-2 hash — never the full value. */
      tier2HashRedacted: string;
      /** @enum {string} */
      state: 'active' | 'flagged' | 'decommissioned';
      serial: number;
      /** Format: date-time */
      createdAt: string;
    };
    UnitsPageDto: {
      data: components['schemas']['UnitResponseDto'][];
      nextCursor: string | null;
    };
    FlagReasonDto: {
      /** @description Why this action is being taken. */
      reason: string;
    };
    ScanEventResponseDto: {
      id: string;
      tenantId: string;
      unitId: string | null;
      batchId: string | null;
      productId: string | null;
      /** @enum {string} */
      tier: 'tier1' | 'tier2';
      /** @description Free-text verdict, e.g. authentic | suspicious | flagged | unknown-tier2. */
      verdict: string;
      /** @enum {string} */
      source: 'qr' | 'manual' | 'sms' | 'api';
      codeRedacted: string;
      geoCountry: string | null;
      geoCity: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    ScanEventsPageDto: {
      data: components['schemas']['ScanEventResponseDto'][];
      nextCursor: string | null;
    };
    ReportResponseDto: {
      id: string;
      tenantId: string;
      reference: string;
      scanEventId: string | null;
      unitId: string | null;
      batchId: string | null;
      productId: string | null;
      verdictAtReport: string;
      sellerName: string | null;
      sellerLocation: string | null;
      /** @enum {string} */
      purchaseChannel:
        | 'open_market'
        | 'street_vendor'
        | 'online_marketplace'
        | 'social_media'
        | 'pharmacy'
        | 'supermarket'
        | 'brand_store'
        | 'other';
      /** Format: date-time */
      purchaseDate: string | null;
      description: string | null;
      /** @enum {string} */
      status: 'new' | 'triaged' | 'investigating' | 'closed';
      /** @enum {string|null} */
      outcome: 'confirmed_counterfeit' | 'legit' | 'insufficient' | null;
      assignedToId: string | null;
      locale: string | null;
      /** Format: date-time */
      closedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ReportsPageDto: {
      data: components['schemas']['ReportResponseDto'][];
      nextCursor: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  MeController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicBatchesController_list: {
    parameters: {
      query?: {
        /** @description Opaque cursor from a previous page. */
        cursor?: string;
        limit?: string;
        productId?: string;
        status?:
          | 'minting'
          | 'minted'
          | 'delivered'
          | 'printed'
          | 'shipped'
          | 'closed'
          | 'failed';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchesPageDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicBatchesController_create: {
    parameters: {
      query?: never;
      header: {
        /** @description Any client-generated unique string, e.g. a UUID. */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePublicBatchDto'];
      };
    };
    responses: {
      /** @description Batch minting started (or already exists for this key). */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateBatchResponseDto'];
        };
      };
      /** @description Missing Idempotency-Key header, or invalid body. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description productId/oemId does not exist for this tenant. */
      402: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Idempotency-Key reused with a different body. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicBatchesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicBatchesController_units: {
    parameters: {
      query?: {
        /** @description Opaque cursor from a previous page. */
        cursor?: string;
        limit?: string;
        state?: 'active' | 'flagged' | 'decommissioned';
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnitsPageDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicUnitsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnitResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicUnitsController_flag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FlagReasonDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnitResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Unit is not in a state this transition allows. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicUnitsController_decommission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FlagReasonDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnitResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Unit is not in a state this transition allows. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicUnitsController_restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FlagReasonDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnitResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Unit is not in a state this transition allows. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicScansController_list: {
    parameters: {
      query?: {
        /** @description Opaque cursor from a previous page. */
        cursor?: string;
        limit?: string;
        batchId?: string;
        unitId?: string;
        /** @description authentic | suspicious | flagged | unknown-tier2 */
        verdict?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScanEventsPageDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicReportsController_list: {
    parameters: {
      query?: {
        /** @description Opaque cursor from a previous page. */
        cursor?: string;
        limit?: string;
        status?: 'new' | 'triaged' | 'investigating' | 'closed';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReportsPageDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PublicReportsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReportResponseDto'];
        };
      };
      /** @description Missing, malformed, revoked, or expired API key. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description The key's scopes don't cover this route. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Not found, or belongs to another tenant — never 403. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
}
