variable "oci_region" {
  default = "uk-london-1"
}

variable "tenancy_ocid" {
  description = "Root compartment (tenancy OCID from ~/.oci/config)."
  type        = string
}

# Free-tier A1 capacity varies per availability domain; on an "Out of host
# capacity" error, bump this to 1 or 2 (uk-london-1 has three ADs) and re-apply.
variable "availability_domain_index" {
  type    = number
  default = 0
}

variable "domain" {
  default = "verifyproduct.app"
}

variable "cloudflare_account_id" {
  type = string
}

# SSH is the deploy/ops path (the app itself is reached only through the
# Cloudflare Tunnel). Locked to your IP; widen deliberately, never to 0.0.0.0/0.
variable "admin_cidr" {
  type = string
}

variable "ssh_public_key" {
  type = string
}

# Deploy key with read access to enendufrankc/verifynNG so cloud-init can clone.
variable "github_deploy_key_private" {
  type      = string
  sensitive = true
}

# Contents of the production .env (generated by scripts/deploy/gen-secrets.sh,
# stored in the password manager, passed here via secrets.auto.tfvars).
variable "production_env" {
  type      = string
  sensitive = true
}
